# Generated by Django 3.2.12 on 2023-07-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Book',
        ),
    ]
