# Generated by Django 3.2.12 on 2023-07-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_auto_20230708_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
