# Generated by Django 3.2.12 on 2023-07-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_auto_20230708_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='bookshop', verbose_name='Imagen'),
        ),
    ]
