# Generated by Django 3.2.12 on 2023-07-10 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshop', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
