# Generated by Django 4.2.3 on 2023-07-19 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookshop", "0009_auto_20230711_0516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="stock",
        ),
    ]
